use wasm_bindgen::prelude::*;
use rust_xlsxwriter::{Workbook, Format, Color, DocProperties};
use calamine::{Reader, Xlsx};
use std::io::Cursor;

#[wasm_bindgen(start)]
pub fn init() {
    console_error_panic_hook::set_once();
}

#[wasm_bindgen]
pub fn process_excel(
    data: &[u8],
    header_color: Option<String>,
    auto_width: Option<f64>,
) -> Result<Vec<u8>, JsValue> {

    // ---------- READ ----------
    let mut excel = Xlsx::new(Cursor::new(data))
        .map_err(|e| JsValue::from_str(&e.to_string()))?;

    let range = excel
        .worksheet_range_at(0)
        .ok_or_else(|| JsValue::from_str("No sheet"))?
        .map_err(|e| JsValue::from_str(&e.to_string()))?;

    // ---------- WRITE ----------
    let mut workbook = Workbook::new();

    // Metadata sin fechas dinámicas
    let props = DocProperties::new().set_title("Generated by PrettySheet");
    workbook.set_properties(&props);

    let worksheet = workbook.add_worksheet();

    // ---------- HEADER FORMAT ----------
    let mut header_format = Format::new().set_bold();

    if let Some(color_hex) = header_color {
        if let Ok(rgb) = parse_hex_color(&color_hex) {
            header_format = header_format.set_background_color(Color::RGB(rgb));
        }
    }

    // ---------- DATA LOOP ----------
    for (r, row) in range.rows().enumerate() {
        for (c, cell) in row.iter().enumerate() {

            if r == 0 {
                worksheet.write_with_format(
                    r as u32,
                    c as u16,
                    &cell.to_string(),
                    &header_format,
                )
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            } else {
                worksheet
                    .write(r as u32, c as u16, &cell.to_string())
                    .map_err(|e| JsValue::from_str(&e.to_string()))?;
            }
        }
    }

    // ---------- WIDTH ----------
    if let Some(width) = auto_width {
        worksheet
            .set_column_width(0, width)
            .map_err(|e| JsValue::from_str(&e.to_string()))?;
    }

    // ---------- SAVE ----------
    workbook
        .save_to_buffer()
        .map_err(|e| JsValue::from_str(&e.to_string()))
}

// ---------- HELPERS ----------

fn parse_hex_color(hex: &str) -> Result<u32, ()> {
    let hex = hex.trim_start_matches('#');
    u32::from_str_radix(hex, 16).map_err(|_| ())
}